language: node_js
matrix:
  include:
    - node_js: "node"
    - node_js: "8"
sudo: false
cache:
  directories:
    - node_modules
dist: trusty
addons:
  chrome: stable
before_script:
  # dump the current versions
  - google-chrome-stable --version
  # start a fresh new Chrome instance
  - google-chrome-stable
        --user-data-dir=$(mktemp -d)
        --no-sandbox --no-first-run --disable-extensions
        --remote-debugging-port=9222 --headless --disable-gpu
        about:blank &>/dev/null &
  # wait for Chrome to start up
  - while ! curl http://localhost:9222 &>/dev/null; do sleep 1; done
